language: ruby
rvm:
  - 2.4.0
cache: bundler
addons:
  postgresql: "9.4"
bundler_args: --without production
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - RACK_ENV=test bundle exec rake db:schema:load
  - RACK_ENV=test bundle exec rspec spec
notifications:
  slack: startwifi:F06TJu0r4obmT3tMrvDWfW1p
